-- GSD Command Center — storage buckets
-- Run after 0002_rls.sql.

insert into storage.buckets (id, name, public)
values
  ('permits', 'permits', false),
  ('payment-proofs', 'payment-proofs', false),
  ('receipts', 'receipts', false),
  ('public-assets', 'public-assets', true)
on conflict (id) do nothing;

-- Admins can do anything in any bucket.
create policy admin_all_storage on storage.objects
  for all using (public.is_admin()) with check (public.is_admin());

-- Anyone can read files in the public-assets bucket (logos, instructor
-- photos, testimonial photos).
create policy public_read_public_assets on storage.objects
  for select to anon using (bucket_id = 'public-assets');

-- Private buckets (permits, payment-proofs, receipts) are read only via
-- short-lived signed URLs generated by admin/server code — no public policy
-- is added for them. The M3 permit upload and M6 payment-proof upload flows
-- will add narrow, purpose-built upload paths (e.g. a signed upload token)
-- rather than opening these buckets to the anon key directly.
